spring:
  datasource:
    initialization-mode: always
    platform: mysql
    url: jdbc:mysql://${CONTENTS_DB_SERVICE_HOST}:${CONTENTS_DB_SERVICE_PORT}/${MYSQL_DATABASE}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
